### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by Tdickson3** [xsy2004/WeChat-Typecho#1]
![image](https://user-images.githubusercontent.com/44915990/98683566-26f10000-23a0-11eb-8c03-a8dcef10b7c4.png)
请问`config.js`这个文件在哪里，`API_SECRET `这个配置项在哪里看。

**Comment by xsy2004** [comment]
不好意思是在/common/vendor.js文件，就把插件安装到小程序之后里面填写的api secret和vendor.is一样
